### ISSUE TITLE
Peer feedback milestone 3

### ISSUE THREAD

**Issue by PolinaRomanchenko** [UBC-MDS/DSCI_522_Group_303#44]
- [x] Change the size of the output plots. Rendering is funny.
- [x] Aggregate on neighborhoods to make that feature more generalized. It will help with skewness and  won't take away from insights value. 
- [x] Add description for needed files/folders/ packages.

**Comment by moniquewong** [comment]
Needed files: 
- need a report folder
- chrome driver selenium
